USE [master]
GO
/****** Object:  Database [ProductsTestDB]    Script Date: 17.10.2017 22:29:09 ******/
CREATE DATABASE [ProductsTestDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProductsTestDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\ProductsTestDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProductsTestDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\ProductsTestDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [ProductsTestDB] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProductsTestDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ProductsTestDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ProductsTestDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ProductsTestDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ProductsTestDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ProductsTestDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ProductsTestDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ProductsTestDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ProductsTestDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ProductsTestDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ProductsTestDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ProductsTestDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ProductsTestDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ProductsTestDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ProductsTestDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ProductsTestDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ProductsTestDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ProductsTestDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ProductsTestDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ProductsTestDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ProductsTestDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ProductsTestDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ProductsTestDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ProductsTestDB] SET RECOVERY FULL 
GO
ALTER DATABASE [ProductsTestDB] SET  MULTI_USER 
GO
ALTER DATABASE [ProductsTestDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ProductsTestDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ProductsTestDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ProductsTestDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ProductsTestDB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'ProductsTestDB', N'ON'
GO
ALTER DATABASE [ProductsTestDB] SET QUERY_STORE = OFF
GO
USE [ProductsTestDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [ProductsTestDB]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 17.10.2017 22:29:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Code] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Product] ON 
GO
INSERT [dbo].[Product] ([Id], [Name], [Code]) VALUES (1, N'პური', N'001')
GO
INSERT [dbo].[Product] ([Id], [Name], [Code]) VALUES (2, N'მარილი', N'002')
GO
SET IDENTITY_INSERT [dbo].[Product] OFF
GO
USE [master]
GO
ALTER DATABASE [ProductsTestDB] SET  READ_WRITE 
GO
